component: frontend
namespace: frontend
image:
  repository: asia-southeast1-docker.pkg.dev/heroic-night-453607-n0/web-app-repository/frontend
  tag: ga-0.0.7
service:
  type: LoadBalancer
  port: 80
  targetPort: 80