component: frontend
namespace: frontend
image:
  repository: asia-southeast1-docker.pkg.dev/heroic-night-453607-n0/web-app-repository/frontend
  tag: ga-0.0.8
replicas: 3
service:
  type: NodePort
  port: 80
  targetPort: 80

backend:
  namespace: backend
  component: backend
  image:
    repository: asia-southeast1-docker.pkg.dev/heroic-night-453607-n0/web-app-repository/backend
    tag: v0.0.4
  replicas: 3
  service:
    type: ClusterIP
    port: 80
    targetPort: 3000