apiVersion: v1
kind: Service
metadata:
  name: {{.Values.backend.component}}-proxy-service
  namespace: {{.Values.namespace}}
spec:
  type: ExternalName
  externalName: {{.Values.backend.component}}-service.{{.Values.backend.namespace}}.svc.cluster.local
  ports:
    - port: 80
