apiVersion: v1
kind: Service
metadata:
  name: {{.Values.backend.component}}-service
  namespace: {{.Values.backend.namespace}}
spec:
  selector:
    app: {{.Values.backend.component}}
  type: {{.Values.backend.service.type}}
  ports:
    - protocol: TCP
      port: {{.Values.backend.service.port}}
      targetPort: {{.Values.backend.service.targetPort}}
